{% set name = "analysis" %}
{% set year = "2019" %}
{% set cycle = "3" %}
{% set version = "0" %}
{% set micro = "1" %}

package:
  name: {{ name }}
  version: {{ year }}C{{ cycle }}.{{ version }}.{{ micro }}

build:
  skip: True  # [py<36]
  number: 2

requirements:
  host:
    - python
  run:
    - amostra <=1.0
    - attrs >=18.0
    - bluesky >=1.5.5,<1.6
    - bluesky-browser
    - bluesky-kafka
    - dask
    - databroker >=0.13.3,<1.0
    - distributed
    - event-model >=1.11.2
    - fabio
    - ffmpeg >=4.0
    - flake8
    - graphviz
    - grid-strategy
    - h5py >=2.9.0
    - intake-bluesky
    - ipykernel
    - ipympl==0.1.1
    - ipython
    - ipywidgets==7.2.1
    - jupyter
    - matplotlib >=3.1.0
    - numpy >=1.14.0
    - openpyxl
    - ophyd >=1.3.3,<1.4
    - oscars
    - peakutils
    - pyepics <3.4.0
    - pyfftw
    - pymongo >=3.7
    - pyqt >=5.6.0
    - python
    - python-graphviz
    - qt >=5.6.0
    - scikit-beam >=0.0.18
    - suitcase-csv
    - suitcase-json-metadata
    - suitcase-jsonl
    - suitcase-mongo
    - suitcase-msgpack
    - suitcase-specfile
    - suitcase-tiff
    - suitcase-utils
    - sympy
    - tornado <5.0.0
    - tzlocal >=1.5
    - xlrd
    - xlwt
    - xray-vision

test:
  imports:
    - bluesky
    - bluesky_browser
    - dask
    - databroker
    - event_model
    - intake_bluesky
    - lmfit
    - matplotlib
    - numpy
    - ophyd
    - oscars
    - peakutils
    - pymongo
    - skbeam
    - suitcase.csv
    - suitcase.json_metadata
    - suitcase.jsonl
    - suitcase.mongo_embedded
    - suitcase.mongo_normalized
    - suitcase.msgpack
    - suitcase.specfile
    - suitcase.tiff_series
    - suitcase.tiff_stack
    - suitcase.utils
    - xray_vision
  commands:
    - python -V
    - ipython -V

about:
  home: https://nsls-ii.github.io/deployment_docs.html
  license: BSD 3-Clause
  license_file: LICENSE
  summary: Analysis metapackage for NSLS-II deployments
  description: |
    Analysis metapackage for NSLS-II deployments. See the deployment
    documentation at https://nsls-ii.github.io/deployment_docs.html.
