{% set name = "analysis" %}
{% set year = "2019" %}
{% set cycle = "3" %}
{% set version = "0" %}

package:
  name: {{ name }}
  version: {{ year }}C{{ cycle }}.{{ version }}

build:
  skip: True  # [py<36]
  number: 2

requirements:
  host:
    - python
  run:
    - amostra
    - attrs >=18.0
    - bluesky >=1.5.5
    - bluesky-browser
    - bluesky-kafka
    - dask
    - databroker >=0.13.0
    - distributed
    - fabio
    - ffmpeg >=4.0  # [not win]
    - flake8
    - graphviz
    - grid-strategy
    - h5py >=2.9.0
    - intake-bluesky
    - ipykernel
    - ipympl==0.1.1
    - ipython
    - ipywidgets==7.2.1
    - jupyter
    - matplotlib >=3.1.0
    - numpy >=1.14.0
    - openpyxl
    - ophyd >=1.3.3
    - oscars
    - peakutils
    - pyfftw
    - pymongo >=3.7
    - pyqt >=5.6.0
    - python
    - python-graphviz
    - qt >=5.6.0
    - scikit-beam
    - sympy
    - tornado <5.0.0
    - tzlocal >=1.5
    - xlrd
    - xlwt
    - xray-vision

test:
  imports:
    - bluesky
    - bluesky_browser
    - dask
    - databroker
    - event_model
    - lmfit
    - matplotlib
    - numpy
    - ophyd
    - oscars
    - peakutils
    - pymongo
    - skbeam
    - xray_vision
    - intake_bluesky
  commands:
    - python -V
    - ipython -V

about:
  home: https://nsls-ii.github.io/deployment_docs.html
  license: BSD 3-Clause
  license_file: LICENSE
  summary: Analysis metapackage for NSLS-II deployments
  description: |
    Analysis metapackage for NSLS-II deployments. See the deployment
    documentation at https://nsls-ii.github.io/deployment_docs.html.
