{% set name = "analysis" %}
{% set year = "2020" %}
{% set cycle = "1" %}
{% set version = "0" %}
{% set micro = "rc1" %}

package:
  name: {{ name|lower }}
  version: {{ year }}C{{ cycle }}.{{ version }}{{ micro }}

build:
  skip: True  # [py<36]
  number: 0

requirements:
  host:
    - python
  run:
    - python
    - amostra <=1.0
    - attrs >=18.0
    - bluesky >=1.6.0rc4
    - bluesky-kafka
    - dask
    - databroker <1.0.0a
    - distributed
    - event-model >=1.13.2
    - fabio
    - ffmpeg >=4.0
    - flake8
    - graphviz
    - grid-strategy
    - h5py >=2.9.0
    - ipykernel
    - ipympl==0.1.1
    - ipython
    - ipywidgets==7.2.1
    - jupyter
    - matplotlib >=3.1.0
    - numpy >=1.14.0
    - openpyxl
    - ophyd >=1.4.0rc4
    - oscars
    - peakutils
    - pyepics >=3.4.1
    - pyfftw
    - pymongo >=3.7
    - pyqt >=5.6.0
    - python-graphviz
    - qt >=5.6.0
    - scikit-beam >=0.0.18
    - suitcase-csv
    - suitcase-json-metadata
    - suitcase-jsonl
    - suitcase-mongo
    - suitcase-msgpack
    - suitcase-specfile
    - suitcase-tiff
    - suitcase-utils
    - sympy
    - tornado
    - tzlocal >=1.5
    - xlrd
    - xlwt
    - xray-vision

test:
  imports:
    - bluesky
    - dask
    - databroker
    - event_model
    - lmfit
    - matplotlib
    - numpy
    - ophyd
    - oscars
    - peakutils
    - pymongo
    - skbeam
    - suitcase.csv
    - suitcase.json_metadata
    - suitcase.jsonl
    - suitcase.mongo_embedded
    - suitcase.mongo_normalized
    - suitcase.msgpack
    - suitcase.specfile
    - suitcase.tiff_series
    - suitcase.tiff_stack
    - suitcase.utils
    - xray_vision
  commands:
    - python -V
    - ipython -V
    - python -c "from distutils.version import LooseVersion; import bluesky; assert LooseVersion(bluesky.__version__) >= '1.6'"
    - python -c "from distutils.version import LooseVersion; import databroker; assert LooseVersion(databroker.__version__) < '1.0'"
    - python -c "from distutils.version import LooseVersion; import ophyd; assert LooseVersion(ophyd.__version__) >= '1.4'"

about:
  home: https://nsls-ii.github.io/deployment_docs.html
  license: BSD 3-Clause
  license_file: LICENSE
  summary: Analysis metapackage for NSLS-II deployments
  description: |
    Analysis metapackage for NSLS-II deployments. See the deployment
    documentation at https://nsls-ii.github.io/deployment_docs.html.
